name: NodeJS CI

on: [push]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '8']
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        with:
          java-version: ${{ matrix.java }}
        uses: actions/setup-java@v1
      - name: Set up NPM
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: mvn package
        run: mvn package -DskipTests
      - name: NPM
        working-directory: ./javascript/src/typescript
        run: |
          npm install
          npm run build
          NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} npm publish
