name: NPM Publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        name: Set up JDK
        with:
          java-version: 1.8
      - name: run mvn package
        run: |
          mvn package -DskipTests
      - name: print auth token
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - name: npm publish
        working-directory: ./javascript/src/typescript
        run: NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} npm publish
